### ISSUE TITLE
'__typeof': identifier not found 

### ISSUE THREAD

**Issue by kinjal20** [Jaskamalkainth/Topcoder#1]
I have used one function as below:
#define FOREACH(itr,v) for(__typeof((v).begin()) itr=(v).begin(); itr!=(v).end();itr++)

function call is as below:
FOREACH(itr,node)
{
// code 
}

I am using  visual Studio 2012. How can I resolve it?

**Comment by Jaskamalkainth** [comment]
If you are using C++11 or C++14, then you can you remove that line and use this instead.
`for(auto itr: node)
{
//code
}
`

**Comment by kinjal20** [comment]
Thank you, its perfect.
